name = "backend"
main = "src/index.ts"
compatibility_date = "2024-10-14"
compatibility_flags = [ "nodejs_compat" ]

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.
eyJhcGlfa2V5IjoiMjEwMzNkMTEtNmYzMy00MTQ3LWI4NDUtMGM5Mzg1Y2I2YWQ5IiwidGVuYW50X2lkIjoiOTUwNzA0YzEzZjExN2V
lNTFmYmU1ZTMyOTRhM2YzN2Y1NDU4Y2Y0YWQ4NjQ5ZmVlM2ZkZjQzMjk5ODMyZTg0MSIsImludGVybmFsX3NlY3JldCI6IjZmOWM0MTY5L
TMyZTEtNDNjYy04MWNlLTk4MTFmYzdiYTFmYSJ9.siiaxyBMiRI8TucfBFtbHgCtjAMLNjoTdRkUYmYrU0o"

