name = "backend"
main = "src/index.ts"
compatibility_date = "2024-10-16"
compatibility_flags = [ "nodejs_compat" ]

[vars]

DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiNGM3OGFlNzMtMjIxYi00ZDA5LWE4MGYtODY5ZWUyNTJmYmQyIiwidGVuYW50X2lkIjoiOTUwNzA0YzEzZjExN2VlNTFmYmU1ZTMyOTRhM2YzN2Y1NDU4Y2Y0YWQ4NjQ5ZmVlM2ZkZjQzMjk5ODMyZTg0MSIsImludGVybmFsX3NlY3JldCI6IjZmOWM0MTY5LTMyZTEtNDNjYy04MWNlLTk4MTFmYzdiYTFmYSJ9.hjFJLrwetRc6fwKMdaOmiB-brZiOY4ThyHjXPmOFX5s"
JWT_SECRET = "somesecret"
